🐞fix: Error: no such container
when run make on github ci, it complains:

 Error: No such container: 2
sudo docker rmi zillionare:1.0.0.a8 2>/dev/null ||:
sudo docker image prune -f --filter dangling=true 2>/dev/null||:
Total reclaimed space: 0B
Error: No such container: dev
Error: No such container: dev
Error: No such container: dev
# omega config
sudo docker cp dev:/apps/omega/omega/config/defaults.yaml setup/docker/rootfs//root/zillionare/omega/config
Error: No such container:path: dev:/apps/omega/omega/config/defaults.yaml

this is caused makefile depends on local docker env

Now it will use testpypi to fetcher artifacts